#ifndef AMINTP_PLATFORM_H
#define AMINTP_PLATFORM_H

#define AMINTP_MIN_OS_MAJOR 2
#define AMINTP_MIN_OS_MINOR 4

#define AMINTP_MIN_CPU "68000"
#define AMINTP_REQUIRES_FPU 0
#define AMINTP_HAS_GUI 0

#define AMINTP_AREXX_PORT "AMINTP"

#endif
